<Project>
    <PropertyGroup>
        <AnalysisLevel>latest</AnalysisLevel>
        <Deterministic>true</Deterministic>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
</Project>
