<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreStack.Abstraction\CoreStack.Abstraction.csproj" />
    <ProjectReference Include="..\CoreStack.Domain\CoreStack.Domain.csproj" />
  </ItemGroup>

</Project>
