<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreStack.Abstraction\CoreStack.Abstraction.csproj" />
    <ProjectReference Include="..\CoreStack.Application\CoreStack.Application.csproj" />
    <ProjectReference Include="..\CoreStack.Domain\CoreStack.Domain.csproj" />
  </ItemGroup>

</Project>
